### PR TITLE
Gif thumbnail

### PR DESCRIPTION
**Pull request by roIyat**
Creates a 5s  gif thumbnail from a webm file

### CODE REVIEW

**Comment by goosehub** [comment]
Can this feature be toggled by admin? Doesn't look like it.

**Comment by roIyat** [comment]
No it's hardcoded. I realize it should better as an option to toggle in instance-config.php

**Comment by goosehub** [comment]
Yeah, I'd recommend off by default and toggle on. Then they'd be no reason I can think of for anyone to object to this feature. Pretty cool feature by the way.

**Comment by ctrlcctrlv** [comment]
Rejected per #290. Hard coded changes are not accepted. Put all your commits in one PR, write a _clear_ rationale for the change, make sure that it's disabled by default, and try again.

**Pull request closed without merging**
