### PR TITLE
Add banners as default functionality & display them on mod login / dashboard when enabled

### PR DESCRIPTION
**Pull request by thedeysu**
No longer will people have to google "random image php script" and add it to their installation! Basically every vichan instance has banners, so there's really no reason to not have this in upstream

I made the default banner. If you don't like it / would like it to be something else, let me know and I'll change that. Perhaps this is a golden opportunity to use a fursona and make people seethe?

I also made banners enabled functionality by default, with pre-set limits to 300x100 (what 99% of sites use anyway)

The rotating banner script is lainchan's original version (without priority banner support - I think "priority banners" are kinda silly and not worth having yet another directory for.

Banner file is named "b.php" because many adblockers heuristically detect anything named "banner.php" as something serving ads and block it.

### CODE REVIEW

**Review by ctrlcctrlv — CHANGES_REQUESTED** [review]
Sorry, this PR has a few issues.

① It will conflict with a board named /banners/. As this is legacy software, we should avoid introducing subtle bugs.
② I try to avoid merging PR's with memes, not because I hate memes, but just to keep the project professional. I'd remove the greentext.

**Comment by thedeysu** [comment]
I have made the requested changes. Should I edit https://github.com/vichan-devel/vichan/blob/a3dc72bddb24248fc3b6ec625e907cd8dfd42415/static/clickme.gif as well? it's rather memey tbh

**Comment by ctrlcctrlv** [comment]
oh regarding h00j's file. he went mega MIA so like his standards were different. i planned to give him this repo and was just letting him do w/e he wanted w/o oversight but then he vanished. it's up to yoou if you want to PR that separately i suppose.

**Comment by technopalms** [comment]
thanks @thedeysu will update my board soon.

**Pull request merged**
