### PR TITLE
Fix editing global pages for 7.4

### PR DESCRIPTION
**Pull request by bebyx**
When trying to edit a global page, you click 'save' and get this:

image

This is a common issue, caused by stricter formatting of 7.4. 

Reference: https://stackoverflow.com/questions/59336951/message-trying-to-access-array-offset-on-value-of-type-null

Simply adding `isset()` to the check of a board URI fixes the issue.

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
[dark9.css](https://github.com/vichan-devel/vichan/pull/469/files#diff-a820ab029c09603b5eb25375c484f88b0b1db670a7876be8d60d53249d2c450c)?

**Comment by bebyx** [comment]
I decided that merging would never happen, so I just focused on my own fork. Please disregard, PR is closed now.

**Comment by bebyx** [comment]
Oops, forgot about that PR. Now that should be fixed (moved commits for 9ch to the other branch), but I can't reopen the PR.

**Comment by bebyx** [comment]
Recreated: https://github.com/vichan-devel/vichan/pull/487

**Pull request closed without merging**
