### PR TITLE
added pagination for search.

### PR DESCRIPTION
**Pull request by H0K4**
main issue i had with search was that it lists all results in one page which increases the load time by a lot and server resources. this simply adds pagination if you get more than 25 results.
If you don't like pagination you can turn it off by simply changing $limit= 25 in search.php to something high like 1000. 
demo is here: https://hokachan.com/search.php?search=busty&board=k (NSFW)
searcpagination

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Why is this needed? Do you not want to use `$config['search']['search_limit']`?

**Comment by H0K4** [comment]
Depends how you use it. if you plan to keep all threads like an archive it's better to use pagination. you don't have to implement if if you don't want to.

**Comment by ctrlcctrlv** [comment]
It's not possible with vichan to keep all threads as an archive...currently. I don't think so anyway, unless @czaks added that and I didn't notice. The reason it's not possible is because every new thread will cause, let's say, if you have 30,000 threads, and 10 threads per page, 3,000 pages to be written to move each thread down by one. When a thread on page 2,999 is bumped up to page 1 (if possible) the same will happen. Archival is not possible(?), therefore I question the necessity of a search function for it.

**Comment by H0K4** [comment]
that's fine. people who need it can just implement it themselves

**Pull request closed without merging**
