### PR TITLE
Update twig to 2.9

### PR DESCRIPTION
**Pull request by perdedora**
Changes made:

- twig folder was deleted. moved functions and filters to `template.php` (class Tinyboard)
- use phpmyadmin intl module instead of patching ourselves (twig dropped support)
- update templates to fix twig deprecations (count, filter remove_whitespace, if inside for tag)
- add twig cache to `cache.php` (twig deleted native support in 2.x)
- updated gettext package version to work with phpmyadmin intl
- add support for twig dump function `{{ dump(var) }}`
- add support for skipping twig cache
- fixed plural in `view_ip.html` (notes, bans and telegrams on record) due to intl module update

### CODE REVIEW

**Comment by basedgentoo** [comment]
We're currently waiting on a code review to take place before taking major merges.
I appreciate this commit. I'll keep you up to date on how the code review is going. It started today.

**Comment by basedgentoo** [comment]
By the way, I welcome you to join #vichan-dev on the KolymaNET IRC if you're interested
Bouncer highly recommended

**Comment by assada** [comment]
Just for history: https://github.com/dead-guru/devichan/pull/13/files

**Comment by ctrlcctrlv** [comment]
Code review from who? You're gonna have to at some point just make a -dev release people can try like @czaks used to.

**Pull request merged**
