### PR TITLE
Add thumbnailing for pdfs feature

### PR DESCRIPTION
**Pull request by KebabLord**
Allow users to thumbnail pdf files using convert. Should work on all imagemagick versions. Disabled by default. Tested on several operating systems with different php versions

### CODE REVIEW

**Comment by KebabLord** [comment]
force push reason: aciddentally removed this commit and created it back since i mixed my branches

**Comment by perdedora** [comment]
I would advise against this. If ghostscript isn't up to date can cause some security concerns. 
https://bugs.archlinux.org/task/59778

Apparently they already fixed, but one should add with feature with caution and even a disclaimer to check your version of ghostscript.

**Comment by ctrlcctrlv** [comment]
I unfortunately agree with @perdedora. This project does not have the resources to deal with PDF thumbnailing, the format is super complicated and rife with security issues regardless of decoder. Either you're not going to support enough files or you're going to be too open to security problems. Keeping it to private forks is fine.

**Comment by KebabLord** [comment]
@crazy4cars69 No it's the opposite, 4ch was hacked because it post-processed the pdfs to create thumbnails by using a very old version of ghostscript. Since vichan doesn't post-process PDFs, vichan is perfectly safe in this scenario. 
Imageboards using vichan fork lainchan are at risk though.  

> also add option to use the static PDF icon for thumbnail

it already exist, just add pdf and the icon to your config.
https://github.com/vichan-devel/vichan/blob/83b644f0f5427427b326681d9baab1b6834e414b/inc/config.php#L859-L864

**Pull request closed without merging**
