### PR TITLE
Add Tinyboard docs from web.archive.org

### PR DESCRIPTION
**Pull request by amsemy**
I saved old (2012-10-16) documentation and convert it to MD.

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Rebase your `add-docs` branch, remove commit https://github.com/vichan-devel/vichan/pull/335/commits/031caa44f15111d3a464e0a283a8b7e05839f991, then force push the branch. I'm not willing to accept your file permissions change, but the creation of a `docs` directory is fine by me.

**Comment by ctrlcctrlv** [comment]
Nevermind, I did it myself. This PR was ***accepted*** (see [origin/master](https://github.com/vichan-devel/vichan/commits/master))&mdash;it only shows up as rejected on Github because I did not accept every commit; to wit, I accepted https://github.com/vichan-devel/vichan/pull/335/commits/107b77617fd55112eef3f9cb9c401a9c84fd8e59 and https://github.com/vichan-devel/vichan/pull/335/commits/ea95c84507f03ef958bffd01b5225075013cab4d, but rejected https://github.com/vichan-devel/vichan/pull/335/commits/031caa44f15111d3a464e0a283a8b7e05839f991, and Github is not yet nuanced enough to show this.

**Comment by ctrlcctrlv** [comment]
See https://github.com/vichan-devel/vichan/commit/47e4af1eb10516e5fc25c6bed1171fded9014c42 and https://github.com/vichan-devel/vichan/wiki/Home/_history

Thanks for  the effort, but I put these in the wiki instead when I found out the wiki was just raw MD files I could push :-)

**Comment by ctrlcctrlv** [comment]
@amsemy Just want to make sure you're happy with how this turned out. Thanks for doing the conversion. If you feel I did it wrong it's open for discussion of course

**Comment by amsemy** [comment]
@ctrlcctrlv It's all right. :) I pulled your changes and closed the branch that is no longer needed.

**Pull request closed without merging**
