### PR TITLE
Moved hardcoded html filepaths into config file for extensibility

### PR DESCRIPTION
**Pull request by hatfield-c**
Many of the HTML files used as templates for the architecture are hardcoded in the Vichan core code. This can interfere with themes modifying the structure of certain pages, such as the file "/templates/index.html", which is used as the default template for boards.

This commit moves much of the hardcoded filepaths from the following core files:
- /inc/display.php
- /inc/functions.php
- /inc/mod/pages.php
- /post.php
- /report.php
- /search.php

and places them into the global "config[]" array at /inc/config.php, as well replacing the filepaths in the core files with references to their appropriate config[] values. 

This ensures that theme developers will have an easier time customizing their instance of Vichan, without the need to modify the core and thus cause problems during updates to the Vichan architecture. Rather, theme developers can instead modify the config values through their instance-config.php file.

### CODE REVIEW

**Comment by rarjpg** [comment]
Maybe use something like `$config['files']['board_index']` instead of plain `$config['file_board_index']`?

**Comment by hatfield-c** [comment]
@rarjpg that is an excellent idea, and will help keep the config file values more organized.

**Comment by rarjpg** [comment]
I'd also suggest to name the key `views` because `files` is ambiguous.

**Review by ctrlcctrlv — CHANGES_REQUESTED** [review]
Resolve merge conflicts.

**Review by ctrlcctrlv — APPROVED** [review]
I did it for you.

**Comment by ctrlcctrlv** [comment]
This commit may create some bugs where the new filepaths are not used when specified (i.e. something was forgotten in the intervening years).

I am merging it anyway. Those can be fixed in followups.

**Pull request merged**
