### PR TITLE
Undo removal of Tinyboard's copyright text

### PR DESCRIPTION
**Pull request by savetheinternet**
At the advice of my attorneys, I've created this pull request to request an undo of @czaks's May 5th 38bf3276e4ffd4b82c4a7bc9eb8e1cf692147bb2 commit.

As per Tinyboard's (infinity's parent's) [original license](https://github.com/vichan-devel/vichan/blob/master/LICENSE.Tinyboard.md):

> All copyright notices and permission notices (including this file) **shall be included and remain unedited** in all copies or substantial portions of the Software. This explicitly includes but is not limited to the Tinyboard copyright notices found in the footers of some template files.

I believe I am owed, as a respected pioneer and the renowned father of this cutting-edge software, the gratitude of not having my signature removed or defaced. Thank you.

By the way, the Tinyboard website is not "dead"; I merely changed some of the content around.

### CODE REVIEW

**Comment by 27chan** [comment]
Your site does not  any support to TinyBoard.

**Comment by neko** [comment]
stop being a nerd @savetheinternet

**Comment by seisatsu** [comment]
He has a point actually, removing his copyright notice was illegal and also an asshole thing to do, considering most of the current code was written by him.

**Comment by czaks** [comment]
I removed the link to a http://tinyboard.org/ in the process of upgrading the copyright
notices, because of it being basically a dead link. I am sure, that the Tinyboard license
is clear, that I didn't violate it in any part when I did so.

I do recognize @savetheinternet's work, and I never said I don't. I removed a link simply
because there is no informative website about the Tinyboard project online anymore. I wanted
to update the footer with an updated Tinyboard website later, for example when it comes
back online.

I am glad that this situation gathered many people interested in Tinyboard licensing
situation, which is pretty unclear to start with. Tinyboard changed its license to a troll
license which contradicts itself, which I didn't pull with vichan and I didn't agree to
relicense my code to, as I am a copyright holder of parts of Tinyboard project too.

We are talking about a former Tinyboard license (later called the Tinyboard license), which
is basically a MIT/X11 license with a fourth paragraph modified from the text:

"All copyright notices and permission notices (including this file) shall be
included and remain unedited in all copies or substantial portions of the
Software."

to the following text:

"All copyright notices and permission notices (including this file) shall be
included and remain unedited in all copies or substantial portions of the
Software. This explicitly includes but is not limited to the Tinyboard copyright
notices found in the footers of some template files."

In my opinion, this license is absolutely equivalent to a MIT/X11 license. There is a
second license vichan code is licensed under: a vichan license, which is equivalent
to a Tinyboard license, which in turn is equivalent a MIT/X11 license, turning in my
opinion the entire vichan and infinity codebases to be licensed under a license that is
equivalent to a MIT/X11 license in every detail.

There are also various notes in the code, including @savetheinternet's own, saying that
the code in a given file is released under a MIT/X11 license, not a Tinyboard license,
which itself appears to be stricter than a MIT/X11 license.

To clear up the situation, for the good of the Tinyboard codebases, I request every
copyright holder of Tinyboard-based projects, to explicitly relicense their contributions
to every Tinyboard, vichan and infinity-based project under a MIT/X11 license in its
most common form. Please do note, that I am not implying, that the MIT/X11 license allows
to remove the copyright notices from Tinyboard template footers.

@savetheinternet, in recognition of your contributions, I let you choose an URL you want
the Tinyboard word to link to, provided that the URL is informative about the Tinyboard
project, and in case you didn't, I will link to your GitHub Tinyboard repository. In any
case, I'm open for the further cooperation on the issue and/or project.

**Comment by jaw-sh** [comment]
@savetheinternet you are one sad little man.

**Comment by mrseth** [comment]
STI, you are a fucking joke, a shitty programmer and an arrogant good-for-nothing codemonkey.

I seriously hope you are just trolling, because referring to this pile of shit as "cutting edge" technology is ludicrous.

**Comment by seisatsu** [comment]
Wow guys it's getting kind of hostile in here. STI did write the original project -- you guys at least owe him that recognition, even if his request is dumb and ill-advised. When Tinyboard came out it was the most "cutting-edge" imageboard software out there. No need to shit on his chest and play down his accomplishments.

**Comment by seisatsu** [comment]
```
<Seisatsu> Do you really want to link stopnerds.org on every vichan page? Why? For what reason?
<Seisatsu> Can't they link something even remotely relevant instead, like your github page?
<savetheinternet> stopnerds is my sole income
<savetheinternet> i created tinyboard only to give stopnerds traffic; without the link, there are no visitors to stopnerds
<Seisatsu> I love you sti
<Seisatsu> I'm going to suffocate
```

**Comment by czaks** [comment]
After a long and a pleasant talk, we came to an agreement, under which tinyboard.org website restores some functionality and we restore the link. I made a small mistake in my analysis: the MIT/X11 license doesn't forbid removal of the copyrights, this has been explicitly changed in Tinyboard version. I will leave this bug open until we get the link back.

**Comment by mrseth** [comment]
<Seisatsu> Do you really want to link stopnerds.org on every vichan page? Why? For what reason?
<Seisatsu> Can't they link something even remotely relevant instead, like your github page?
<savetheinternet> stopnerds is my sole income
<savetheinternet> i created tinyboard only to give stopnerds traffic; without the link, there are no visitors to stopnerds
<Seisatsu> I love you sti
<Seisatsu> I'm going to suffocate


[KIKERY INTENSIFIES]

**Comment by milezzz** [comment]
RIP theinternet.

**Comment by femanon** [comment]
save the internet

**Comment by ctrlcctrlv** [comment]
>At the advice of my attorneys

wew lad

**Comment by ctrlcctrlv** [comment]
Remove rejected pull request from the open PR queue.

**Pull request closed without merging**
